services:
  backend-gateway-web-app:
    container_name: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__Writer__GrpcApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_GRPC_API_ADDRESS}
      - App__Writer__RestApiAddress=${MY_SERVICE_BACKEND_GATEWAY_WEB_APP_CONFIG_WRITER_REST_API_ADDRESS}
    networks:
      - network-backend
    depends_on:
      backend-writer-web-app:
        condition: service_started

  backend-reader-inbox-cleaner-app:
    container_name: ${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_IMAGE_NAME}
    environment:
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_READER_INBOX_CLEANER_APP_CONFIG_POSTGRESQL_USERID}
    networks:
      - network-backend

  backend-reader-inbox-consumer-app:
    container_name: ${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_IMAGE_NAME}
    environment:
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_POSTGRESQL_USERID}
      - App__RabbitMQ__HostName=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_HOSTNAME}
      - App__RabbitMQ__Password=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_PASSWORD}
      - App__RabbitMQ__Port=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_PORT}
      - App__RabbitMQ__UserName=${MY_SERVICE_BACKEND_READER_INBOX_CONSUMER_APP_CONFIG_RABBITMQ_USERNAME}
    networks:
      - network-backend

  backend-writer-outbox-cleaner-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_IMAGE_NAME}
    environment:
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_CLEANER_APP_CONFIG_POSTGRESQL_USERID}
    networks:
      - network-backend

  backend-writer-outbox-producer-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_IMAGE_NAME}
    environment:
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_POSTGRESQL_USERID}
      - App__RabbitMQ__HostName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_RABBITMQ_HOSTNAME}
      - App__RabbitMQ__Password=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_RABBITMQ_PASSWORD}
      - App__RabbitMQ__Port=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_RABBITMQ_PORT}
      - App__RabbitMQ__UserName=${MY_SERVICE_BACKEND_WRITER_OUTBOX_PRODUCER_APP_CONFIG_RABBITMQ_USERNAME}
    networks:
      - network-backend
      
  backend-writer-web-app:
    container_name: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONTAINER_NAME}
    image: ${MY_SERVICE_BACKEND_WRITER_WEB_APP_IMAGE_NAME}
    environment:
      - App__Authentication__Key=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_AUTHENTICATION_KEY}
      - App__PostgreSQL__Password=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PASSWORD}
      - App__PostgreSQL__Port=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_PORT}
      - App__PostgreSQL__Server=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_SERVER}
      - App__PostgreSQL__UserId=${MY_SERVICE_BACKEND_WRITER_WEB_APP_CONFIG_POSTGRESQL_USERID}
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true
