services:
  external-rabbitmq:
    container_name: ${MY_SERVICE_EXTERNAL_RABBITMQ_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_RABBITMQ_IMAGE}
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
    #restart: unless-stopped
    networks:
      - network-backend

  external-pgadmin:
    container_name: ${MY_SERVICE_EXTERNAL_PGADMIN_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_PGADMIN_IMAGE}
    environment:
      - PGADMIN_CONFIG_SERVER_MODE
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    networks:
      - network-backend

  external-postgres:
    container_name: ${MY_SERVICE_EXTERNAL_POSTGRES_CONTAINER_NAME}
    image: ${MY_SERVICE_EXTERNAL_POSTGRES_IMAGE}
    environment:
      - PGDATA
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - network-backend

networks:
  network-backend:
    attachable: true

