global using Ardalis.Result;
global using Grpc.Core;
global using Makc2025.Dummy.Gateway.DomainUseCases.App.Action.Command;
global using Makc2025.Dummy.Gateway.DomainUseCases.App.Actions.Login;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Action.Command;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Action.Query;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Actions.Create;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Actions.Delete;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Actions.Get;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Actions.GetList;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.Actions.Update;
global using Makc2025.Dummy.Gateway.DomainUseCases.DummyItem.DTOs;
global using Makc2025.Dummy.Gateway.Infrastructure.Grpc.App.Action.Command;
global using Makc2025.Dummy.Gateway.Infrastructure.Grpc.DummyItem.Action.Command;
global using Makc2025.Dummy.Gateway.Infrastructure.Grpc.DummyItem.Action.Query;
global using Makc2025.Dummy.Shared.Core.App;
global using Makc2025.Dummy.Shared.Core.Http;
global using Makc2025.Dummy.Shared.Infrastructure.Grpc;
global using Makc2025.Dummy.Writer.Infrastructure.Grpc.App;
global using Makc2025.Dummy.Writer.Infrastructure.Grpc.DummyItem;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using WriterAppGrpcClient = Makc2025.Dummy.Writer.Infrastructure.Grpc.App.App.AppClient;
global using WriterDummyItemGrpcClient = Makc2025.Dummy.Writer.Infrastructure.Grpc.DummyItem.DummyItem.DummyItemClient;
