global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using Ardalis.Result;
global using DotEnv.Core;
global using Makc2025.Dummy.Shared.Core.App;
