global using Makc2025.Dummy.Shared.DomainUseCases.Db.SQL;
global using Makc2025.Dummy.Writer.DomainModel.AppEvent.Entity;
global using Makc2025.Dummy.Writer.DomainModel.AppEventPayload.Entity;
global using Makc2025.Dummy.Writer.DomainModel.DummyItem.Entity;
global using Makc2025.Dummy.Writer.Infrastructure.PostgreSQL.App.Db.Settings;
global using Makc2025.Dummy.Writer.Infrastructure.PostgreSQL.AppEvent.Entity.Db;
global using Makc2025.Dummy.Writer.Infrastructure.PostgreSQL.AppEventPayload.Entity.Db;
global using Makc2025.Dummy.Writer.Infrastructure.PostgreSQL.DummyItem.Entity.Db;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using AppDbSettingsBase = Makc2025.Dummy.Writer.DomainModel.App.Db.AppDbSettings;
global using AppDbSettingsEntitiesBase = Makc2025.Dummy.Writer.DomainModel.App.Db.Settings.AppDbSettingsEntities;
global using AppEventEntityDbSettingsBase = Makc2025.Dummy.Writer.DomainModel.AppEvent.Entity.Db.AppEventEntityDbSettings;
global using AppEventPayloadEntityDbSettingsBase = Makc2025.Dummy.Writer.DomainModel.AppEventPayload.Entity.Db.AppEventPayloadEntityDbSettings;
global using DummyItemEntityDbSettingsBase = Makc2025.Dummy.Writer.DomainModel.DummyItem.Entity.Db.DummyItemEntityDbSettings;
